export function apply(db) {
  db.exec([
    "CREATE TABLE IF NOT EXISTS assistant_agent_runs (",
    "  id TEXT PRIMARY KEY NOT NULL,",
    "  owner TEXT NOT NULL CHECK (length(owner) BETWEEN 1 AND 200),",
    "  channel TEXT NOT NULL CHECK (length(channel) BETWEEN 1 AND 100),",
    "  conversation_id_hash TEXT NOT NULL DEFAULT '' CHECK (",
    "    conversation_id_hash = ''",
    "    OR (length(conversation_id_hash) = 64 AND conversation_id_hash NOT GLOB '*[^0-9a-f]*')",
    "  ),",
    "  event_id_hash TEXT NOT NULL DEFAULT '' CHECK (",
    "    event_id_hash = ''",
    "    OR (length(event_id_hash) = 64 AND event_id_hash NOT GLOB '*[^0-9a-f]*')",
    "  ),",
    "  request_hash TEXT NOT NULL CHECK (",
    "    length(request_hash) = 64 AND request_hash NOT GLOB '*[^0-9a-f]*'",
    "  ),",
    "  agent_id TEXT NOT NULL CHECK (length(agent_id) BETWEEN 1 AND 64),",
    "  agent_version TEXT NOT NULL CHECK (length(agent_version) BETWEEN 1 AND 40),",
    "  task_type TEXT NOT NULL CHECK (length(task_type) BETWEEN 1 AND 64),",
    "  contract_version TEXT NOT NULL CHECK (length(contract_version) BETWEEN 1 AND 100),",
    "  status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'fallback', 'failed')),",
    "  input_snapshot_hash TEXT NOT NULL CHECK (",
    "    length(input_snapshot_hash) = 64 AND input_snapshot_hash NOT GLOB '*[^0-9a-f]*'",
    "  ),",
    "  input_json TEXT NOT NULL CHECK (json_valid(input_json)),",
    "  output_snapshot_hash TEXT CHECK (",
    "    output_snapshot_hash IS NULL",
    "    OR (length(output_snapshot_hash) = 64 AND output_snapshot_hash NOT GLOB '*[^0-9a-f]*')",
    "  ),",
    "  output_json TEXT CHECK (output_json IS NULL OR json_valid(output_json)),",
    "  source TEXT NOT NULL DEFAULT 'pending' CHECK (length(source) BETWEEN 1 AND 100),",
    "  model_provider TEXT CHECK (model_provider IS NULL OR length(model_provider) BETWEEN 1 AND 100),",
    "  model_name TEXT CHECK (model_name IS NULL OR length(model_name) BETWEEN 1 AND 200),",
    "  fallback_reason TEXT CHECK (fallback_reason IS NULL OR length(fallback_reason) BETWEEN 1 AND 200),",
    "  source_refs_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(source_refs_json)),",
    "  confirmation_status TEXT NOT NULL DEFAULT 'not_required' CHECK (",
    "    confirmation_status IN ('not_required', 'preview', 'pending', 'confirmed', 'rejected')",
    "  ),",
    "  error_code TEXT CHECK (error_code IS NULL OR length(error_code) BETWEEN 1 AND 200),",
    "  created_at TEXT NOT NULL,",
    "  completed_at TEXT,",
    "  updated_at TEXT NOT NULL,",
    "  UNIQUE (owner, channel, request_hash)",
    ");",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_assistant_agent_runs_event",
    "  ON assistant_agent_runs(owner, channel, event_id_hash)",
    "  WHERE event_id_hash != '';",
    "CREATE INDEX IF NOT EXISTS idx_assistant_agent_runs_owner_status",
    "  ON assistant_agent_runs(owner, status, created_at DESC);",
    "CREATE INDEX IF NOT EXISTS idx_assistant_agent_runs_agent",
    "  ON assistant_agent_runs(owner, agent_id, task_type, created_at DESC);",
  ].join("\n"));
}
