export const SALES_WORKBENCH_API_CONTRACT_VERSION = "2026-08-07";

export const SALES_WORKBENCH_API_SCHEMAS = {
  customer: {
    id: "string",
    version: "positiveInteger",
    name: "string",
    region: "nullableString",
    type: "nullableString",
    level: "nullableString",
    owner: "nullableString",
    contact: "nullableString",
    relation: "number",
    stakeholders: "array",
    decisionChain: "array",
    historyProjects: "array",
    infrastructure: "array",
    syncPreview: "array",
    budget: "nullableString",
    summary: "nullableString",
    needs: "array",
    risks: "array",
    opportunities: "array",
  },
  opportunity: {
    id: "string",
    version: "positiveInteger",
    customerId: "string",
    name: "string",
    customer: "nullableString",
    stage: "nullableString",
    amount: "nullableString",
    owner: "nullableString",
    probability: "number",
    days: "number",
    requirements: "array",
    competitors: "array",
    solutionDirection: "array",
    sourceRecord: "nullableString",
    risk: "nullableString",
    next: "nullableString",
    tone: "nullableString",
  },
  actionItem: {
    id: "string",
    version: "positiveInteger",
    customerId: "nullableString",
    opportunityId: "nullableString",
    title: "string",
    customer: "nullableString",
    reason: "nullableString",
    due: "nullableString",
    assignee: "nullableString",
    priority: "string",
    status: "string",
    sourceRecordId: "nullableString",
    tone: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  riskItem: {
    id: "string",
    version: "positiveInteger",
    customerId: "nullableString",
    opportunityId: "nullableString",
    title: "string",
    target: "string",
    score: "number",
    severity: "string",
    status: "string",
    evidence: "string",
    action: "string",
    assignee: "nullableString",
    due: "nullableString",
    sourceType: "string",
    sourceId: "nullableString",
    tone: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  knowledgeItem: {
    id: "string",
    version: "positiveInteger",
    title: "string",
    category: "nullableString",
    tags: "array",
    summary: "nullableString",
    content: "nullableString",
    source: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  quickRecord: {
    id: "string",
    version: "positiveInteger",
    rawContent: "string",
    occurredAt: "nullableString",
    sourceChannel: "nullableString",
    customerId: "nullableString",
    opportunityId: "nullableString",
    status: "string",
  },
  quickRecordHistory: {
    id: "string",
    version: "positiveInteger",
    rawContent: "string",
    occurredAt: "nullableString",
    sourceChannel: "nullableString",
    customerId: "nullableString",
    opportunityId: "nullableString",
    status: "string",
    analysis: "nullableObject",
    confirmations: "array",
    confirmedTargets: "array",
    syncLog: "array",
  },
  aiInsight: {
    id: "string",
    quickRecordId: "string",
    source: "string",
    confidence: "number",
    customer: "object",
    opportunity: "object",
    weekly: "object",
    summary: "object",
  },
  manualConfirmation: {
    id: "string",
    quickRecordId: "string",
    target: "string",
    confirmedBy: "nullableString",
    note: "nullableString",
    createdAt: "string",
  },
  weeklyReport: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    periodStart: "string",
    periodEnd: "string",
    status: "string",
    content: "string",
    sourceRefs: "array",
  },
  solutionDraft: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    artifactType: "string",
    title: "string",
    customerId: "string",
    opportunityId: "string",
    status: "string",
    content: "string",
    sourceRefs: "array",
    createdAt: "string",
    updatedAt: "string",
  },
  aiSuggestion: {
    id: "string",
    type: "string",
    title: "string",
    status: "string",
    content: "string",
    sourceRefs: "array",
    createdAt: "string",
  },
  salesDecisionAnalysis: {
    id: "string",
    version: "positiveInteger",
    analysisType: "string",
    industry: "string",
    customerId: "nullableString",
    opportunityId: "nullableString",
    quickRecordId: "nullableString",
    input: "object",
    analysis: "object",
    source: "string",
    createdBy: "string",
    createdAt: "string",
  },
  dashboardSummary: {
    metrics: "object",
    priorityActions: "array",
    customerHeat: "array",
    recentRecords: "array",
    opportunities: "array",
    rhythm: "array",
    stageCounts: "array",
    generatedAt: "string",
  },
  visitItinerary: {
    id: "string",
    version: "positiveInteger",
    title: "string",
    visitDate: "string",
    status: "string",
    request: "object",
    plan: "object",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpensePayment: {
    id: "string",
    expenseId: "string",
    sequence: "positiveInteger",
    paidAt: "string",
    merchant: "nullableString",
    amountCents: "nonNegativeInteger",
    reimbursementCents: "nonNegativeInteger",
    fundingSource: "string",
    paymentMethod: "string",
    accountLast4: "nullableString",
    differenceReason: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseAttachment: {
    id: "string",
    expenseId: "string",
    paymentIds: "array",
    sequence: "positiveInteger",
    kind: "string",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    coveredCents: "nonNegativeInteger",
    notes: "nullableString",
    createdBy: "string",
    createdAt: "string",
    contentUrl: "string",
  },
  travelExpense: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    referenceCode: "string",
    occurredOn: "string",
    category: "string",
    purpose: "string",
    merchant: "nullableString",
    itineraryId: "nullableString",
    customerId: "nullableString",
    invoiceStatus: "string",
    notes: "nullableString",
    payments: "array",
    attachments: "array",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseAdvance: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    weekStart: "string",
    status: "string",
    requestedCents: "nonNegativeInteger",
    receivedCents: "nonNegativeInteger",
    requestedOn: "nullableString",
    receivedOn: "nullableString",
    purpose: "string",
    notes: "nullableString",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseDocumentCandidate: {
    expenseId: "string",
    expenseReferenceCode: "string",
    expenseVersion: "positiveInteger",
    expenseOccurredOn: "string",
    category: "string",
    purpose: "string",
    paymentId: "string",
    paidAt: "string",
    merchant: "nullableString",
    amountCents: "nonNegativeInteger",
    reimbursementCents: "nonNegativeInteger",
  },
  travelExpenseDocumentInbox: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    source: "string",
    sourceRef: "nullableString",
    documentKind: "string",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    sha256: "string",
    status: "string",
    extractedText: "nullableString",
    recognition: "nullableObject",
    matchedExpenseId: "nullableString",
    matchedPaymentId: "nullableString",
    errorCode: "nullableString",
    candidates: "array",
    attachmentId: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  invoiceDocument: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    source: "string",
    sourceRef: "nullableString",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    sha256: "string",
    extractedText: "nullableString",
    ocr: "nullableObject",
    model: "nullableObject",
    conflicts: "array",
    invoiceCode: "nullableString",
    invoiceNumber: "nullableString",
    issuedOn: "nullableString",
    sellerName: "nullableString",
    buyerName: "nullableString",
    suggestedCategory: "nullableString",
    amountExTaxCents: "nullableNumber",
    taxCents: "nullableNumber",
    totalCents: "nullableNumber",
    status: "string",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
    contentUrl: "string",
  },
  invoiceMatch: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    invoiceId: "string",
    expenseId: "string",
    paymentId: "nullableString",
    allocatedCents: "positiveInteger",
    matchMethod: "string",
    score: "nullableNumber",
    rationale: "array",
    state: "string",
    confirmedBy: "nullableString",
    confirmedAt: "nullableString",
    revokedBy: "nullableString",
    revokedAt: "nullableString",
    createdBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseNoInvoiceConfirmation: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    expenseId: "string",
    paymentId: "nullableString",
    amountSnapshotCents: "positiveInteger",
    reason: "string",
    confirmedBy: "string",
    confirmedAt: "string",
    revokedBy: "nullableString",
    revokedAt: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  invoiceMatchCandidate: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    weekStart: "string",
    invoiceId: "string",
    expenseId: "string",
    paymentId: "nullableString",
    proposedCents: "positiveInteger",
    score: "positiveInteger",
    rationale: "array",
    status: "string",
    acceptedMatchId: "nullableString",
    decidedBy: "nullableString",
    decidedAt: "nullableString",
    createdBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseInvoiceCoverage: {
    weekStart: "string",
    reimbursementCents: "nonNegativeInteger",
    confirmedCoverageCents: "nonNegativeInteger",
    missingInvoiceCents: "nonNegativeInteger",
    noInvoiceConfirmedCents: "nonNegativeInteger",
    unacknowledgedMissingCents: "nonNegativeInteger",
    expenseCount: "nonNegativeInteger",
  },
};

function describeValue(value) {
  if (Array.isArray(value)) return "array";
  if (value === null) return "null";
  return typeof value;
}

function isExpectedType(value, descriptor) {
  if (descriptor === "array") return Array.isArray(value);
  if (descriptor === "object") return value !== null && typeof value === "object" && !Array.isArray(value);
  if (descriptor === "nullableObject") return value === null || (typeof value === "object" && !Array.isArray(value));
  if (descriptor === "string") return typeof value === "string";
  if (descriptor === "number") return typeof value === "number" && Number.isFinite(value);
  if (descriptor === "positiveInteger") return Number.isSafeInteger(value) && value > 0;
  if (descriptor === "nonNegativeInteger") return Number.isSafeInteger(value) && value >= 0;
  if (descriptor === "nullableString") return value === null || typeof value === "string";
  if (descriptor === "nullableNumber") return value === null || (typeof value === "number" && Number.isFinite(value));
  throw new Error(`Unknown API contract descriptor: ${descriptor}`);
}

export function collectApiEntityErrors(entityName, value, path = entityName) {
  const schema = SALES_WORKBENCH_API_SCHEMAS[entityName];
  if (!schema) return [`${path}: unknown API contract entity "${entityName}"`];
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return [`${path}: expected object, received ${describeValue(value)}`];
  }

  const errors = [];
  for (const [field, descriptor] of Object.entries(schema)) {
    if (!(field in value)) {
      errors.push(`${path}.${field}: missing required field`);
      continue;
    }
    if (!isExpectedType(value[field], descriptor)) {
      errors.push(`${path}.${field}: expected ${descriptor}, received ${describeValue(value[field])}`);
    }
  }
  return errors;
}

export function assertApiEntity(entityName, value, path = entityName) {
  const errors = collectApiEntityErrors(entityName, value, path);
  if (errors.length > 0) {
    throw new TypeError(`Sales workbench API contract violation:\n${errors.join("\n")}`);
  }
  return value;
}

export function assertApiCollection(entityName, values, path = `${entityName}[]`) {
  if (!Array.isArray(values)) {
    throw new TypeError(`Sales workbench API contract violation:\n${path}: expected array, received ${describeValue(values)}`);
  }

  values.forEach((value, index) => assertApiEntity(entityName, value, `${path}[${index}]`));
  return values;
}
