export const SALES_WORKBENCH_API_CONTRACT_VERSION = "2026-09-06";

export const SALES_WORKBENCH_API_SCHEMAS = {
  customer: {
    id: "string",
    version: "positiveInteger",
    name: "string",
    region: "nullableString",
    type: "nullableString",
    level: "nullableString",
    owner: "nullableString",
    contact: "nullableString",
    relation: "number",
    stakeholders: "array",
    decisionChain: "array",
    historyProjects: "array",
    infrastructure: "array",
    syncPreview: "array",
    budget: "nullableString",
    summary: "nullableString",
    needs: "array",
    risks: "array",
    opportunities: "array",
    aliases: "optional:stringArray",
    tags: "optional:stringArray",
    createdAt: "optional:nullableString",
    updatedAt: "optional:nullableString",
  },
  opportunity: {
    id: "string",
    version: "positiveInteger",
    customerId: "string",
    name: "string",
    customer: "nullableString",
    stage: "nullableString",
    amount: "nullableString",
    owner: "nullableString",
    probability: "number",
    days: "number",
    requirements: "array",
    competitors: "array",
    solutionDirection: "array",
    sourceRecord: "nullableString",
    risk: "nullableString",
    next: "nullableString",
    tone: "nullableString",
  },
  actionItem: {
    id: "string",
    version: "positiveInteger",
    customerId: "nullableString",
    opportunityId: "nullableString",
    title: "string",
    customer: "nullableString",
    reason: "nullableString",
    due: "nullableString",
    assignee: "nullableString",
    priority: "string",
    status: "string",
    sourceRecordId: "nullableString",
    tone: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  riskItem: {
    id: "string",
    version: "positiveInteger",
    customerId: "nullableString",
    opportunityId: "nullableString",
    title: "string",
    target: "string",
    score: "number",
    severity: "string",
    status: "string",
    evidence: "string",
    action: "string",
    assignee: "nullableString",
    due: "nullableString",
    sourceType: "string",
    sourceId: "nullableString",
    tone: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  knowledgeItem: {
    id: "string",
    version: "positiveInteger",
    title: "string",
    category: "nullableString",
    tags: "array",
    summary: "nullableString",
    content: "nullableString",
    source: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  quickRecord: {
    id: "string",
    version: "positiveInteger",
    rawContent: "string",
    occurredAt: "nullableString",
    sourceChannel: "nullableString",
    customerId: "nullableString",
    opportunityId: "nullableString",
    status: "string",
    confirmationPreviewId: "nullableString",
    confirmationPreviewStatus: "nullableString",
  },
  quickRecordHistory: {
    id: "string",
    version: "positiveInteger",
    rawContent: "string",
    occurredAt: "nullableString",
    sourceChannel: "nullableString",
    customerId: "nullableString",
    opportunityId: "nullableString",
    status: "string",
    confirmationPreviewId: "nullableString",
    confirmationPreviewStatus: "nullableString",
    analysis: "nullableObject",
    confirmations: "array",
    confirmedTargets: "array",
    syncLog: "array",
  },
  quickRecordConfirmationPreview: {
    schemaVersion: "string",
    id: "string",
    identity: "string",
    owner: "string",
    status: "string",
    revision: "positiveInteger",
    quickRecordId: "string",
    quickRecordVersion: "positiveInteger",
    quickRecordStatus: "string",
    analysisVersionId: "string",
    analysisStatus: "string",
    summary: "object",
    evidence: "array",
    summaryHash: "string",
    evidenceHash: "string",
    draftHash: "string",
    items: "array",
    requiresHumanConfirmation: "boolean",
    automaticWriteAllowed: "boolean",
    createdWithUnsavedChanges: "boolean",
    createdAt: "string",
    updatedAt: "string",
    completedAt: "nullableString",
    cancelledAt: "nullableString",
    cancelledBy: "nullableString",
    replayed: "boolean",
    confirmationBlocked: "boolean",
    bulkEligibleItemIds: "array",
  },
  quickRecordConfirmationOutcome: {
    status: "string",
    preview: "object",
    confirmedItems: "array",
    excludedItems: "array",
    writeback: "boolean",
    replayed: "boolean",
    reason: "nullableString",
    details: "nullableObject",
  },
  aiInsight: {
    id: "string",
    quickRecordId: "string",
    source: "string",
    confidence: "number",
    customer: "object",
    opportunity: "object",
    weekly: "object",
    summary: "object",
  },
  manualConfirmation: {
    id: "string",
    quickRecordId: "string",
    target: "string",
    confirmedBy: "nullableString",
    note: "nullableString",
    createdAt: "string",
  },
  weeklyReport: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    periodStart: "string",
    periodEnd: "string",
    status: "string",
    content: "string",
    entries: "array",
    sourceRefs: "array",
    source: "string",
    fallbackReason: "nullableString",
  },
  solutionDraft: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    artifactType: "string",
    title: "string",
    customerId: "string",
    opportunityId: "string",
    status: "string",
    content: "string",
    sourceRefs: "array",
    source: "string",
    fallbackReason: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  aiSuggestion: {
    id: "string",
    version: "positiveInteger",
    type: "string",
    title: "string",
    status: "string",
    content: "string",
    draft: "string",
    confidence: "number",
    sourceRefs: "array",
    confirmationPreview: "object",
    source: "string",
    fallbackReason: "nullableString",
    createdAt: "string",
    updatedAt: "string",
    confirmedAt: "nullableString",
    cancelledAt: "nullableString",
  },
  visitTemperatureSuggestion: {
    id: "string",
    identity: "string",
    status: "string",
    owner: "string",
    visitId: "string",
    customerId: "string",
    previousValue: "number",
    suggestedValue: "number",
    delta: "number",
    confidence: "number",
    customerVersion: "positiveInteger",
    facts: "array",
    inferences: "array",
    sourceRefs: "array",
    requiresHumanConfirmation: "boolean",
    writebackAllowed: "boolean",
    createdAt: "string",
    expiresAt: "string",
    confirmedAt: "nullableString",
    cancelledAt: "nullableString",
    replayed: "boolean",
    writeback: "boolean",
    reason: "string",
  },
  visitTemperatureOutcome: {
    status: "string",
    suggestion: "nullableObject",
    customer: "nullableObject",
    currentCustomer: "nullableObject",
    writeback: "boolean",
    replayed: "boolean",
    reason: "string",
  },
  salesDecisionAnalysis: {
    id: "string",
    version: "positiveInteger",
    analysisType: "string",
    industry: "string",
    customerId: "nullableString",
    opportunityId: "nullableString",
    quickRecordId: "nullableString",
    input: "object",
    analysis: "object",
    source: "string",
    createdBy: "string",
    createdAt: "string",
  },
  dashboardSummary: {
    metrics: "object",
    priorityActions: "array",
    customerHeat: "array",
    recentRecords: "array",
    opportunities: "array",
    rhythm: "array",
    stageCounts: "array",
    todayFocus: "object",
    weeklyTrend: "object",
    generatedAt: "string",
  },
  proactiveAssistant: {
    schemaVersion: "string",
    modelVersion: "string",
    source: "string",
    generatedAt: "string",
    staleDays: "positiveInteger",
    limit: "positiveInteger",
    items: "array",
    counts: "object",
    truncated: "boolean",
    writebackPolicy: "object",
  },
  proactiveConfirmationPreview: {
    schemaVersion: "string",
    id: "string",
    owner: "string",
    suggestionId: "string",
    target: "string",
    revision: "positiveInteger",
    status: "string",
    customerId: "string",
    opportunityId: "string",
    opportunityVersion: "positiveInteger",
    customerVersion: "positiveInteger",
    previewDigest: "string",
    preview: "object",
    snapshot: "object",
    createdAt: "string",
    updatedAt: "string",
    expiresAt: "string",
    confirmedAt: "nullableString",
    confirmedBy: "nullableString",
    resultItemId: "nullableString",
    replayed: "boolean",
  },
  proactiveAssistantConfirmationRequest: {
    confirmationPreviewId: "string",
    target: "string",
    customerId: "string",
    opportunityId: "string",
    expectedOpportunityVersion: "positiveInteger",
    expectedCustomerVersion: "positiveInteger",
    previewDigest: "string",
    preview: "object",
  },
  proactiveAssistantConfirmationOutcome: {
    status: "string",
    target: "string",
    replayed: "boolean",
    proactiveId: "string",
    suggestionId: "string",
    confirmationPreviewId: "string",
    action: "nullableObject",
    risk: "nullableObject",
  },
  visitItinerary: {
    id: "string",
    version: "positiveInteger",
    title: "string",
    visitDate: "string",
    status: "string",
    request: "object",
    plan: "object",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpensePayment: {
    id: "string",
    expenseId: "string",
    sequence: "positiveInteger",
    paidAt: "string",
    merchant: "nullableString",
    amountCents: "nonNegativeInteger",
    reimbursementCents: "nonNegativeInteger",
    fundingSource: "string",
    paymentMethod: "string",
    accountLast4: "nullableString",
    differenceReason: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseAttachment: {
    id: "string",
    expenseId: "string",
    paymentIds: "array",
    sequence: "positiveInteger",
    kind: "string",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    coveredCents: "nonNegativeInteger",
    notes: "nullableString",
    createdBy: "string",
    createdAt: "string",
    contentUrl: "string",
  },
  travelExpense: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    referenceCode: "string",
    occurredOn: "string",
    category: "string",
    purpose: "string",
    merchant: "nullableString",
    itineraryId: "nullableString",
    customerId: "nullableString",
    invoiceStatus: "string",
    notes: "nullableString",
    tripRegion: "nullableString",
    tripRegionSource: "nullableString",
    payments: "array",
    attachments: "array",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  shortcutBookkeepingLedgerReceipt: {
    entryId: "string",
    expenseId: "string",
    paymentId: "string",
    referenceCode: "string",
    occurredOn: "string",
    weekStart: "string",
    amountCents: "nonNegativeInteger",
    reimbursementCents: "nonNegativeInteger",
    attachmentStatus: "string",
  },
  shortcutBookkeepingReview: {
    id: "string",
    status: "string",
    targetSystem: "string",
    ledgerName: "string",
    entryType: "string",
    category: "string",
    subcategory: "nullableString",
    note: "nullableString",
    warnings: "array",
    expenseId: "nullableString",
    paymentId: "nullableString",
    expenseReferenceCode: "nullableString",
    remoteId: "nullableString",
    remoteReference: "nullableString",
    remoteStatus: "nullableString",
    replayed: "boolean",
    ledgerReceipt: "nullableObject",
    rawText: "string",
    analysis: "nullableObject",
    analysisProvider: "nullableString",
    analysisModel: "nullableString",
    errorCode: "nullableString",
    attemptCount: "nonNegativeInteger",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseWorkbench: {
    weekStart: "string",
    expenses: "array",
    advances: "array",
    bookkeepingReviews: "array",
    regionProfile: "object",
    recentLedgerReceipts: "array",
    generatedAt: "string",
  },
  travelExpenseRegionProfile: {
    weekStart: "string",
    weekEnd: "string",
    version: "nonNegativeInteger",
    cities: "array",
    defaultCity: "nullableString",
    dateOverrides: "array",
    createdAt: "nullableString",
    updatedAt: "nullableString",
  },
  travelExpenseAdvance: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    weekStart: "string",
    status: "string",
    requestedCents: "nonNegativeInteger",
    receivedCents: "nonNegativeInteger",
    requestedOn: "nullableString",
    receivedOn: "nullableString",
    purpose: "string",
    notes: "nullableString",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseDocumentCandidate: {
    expenseId: "string",
    expenseReferenceCode: "string",
    expenseVersion: "positiveInteger",
    expenseOccurredOn: "string",
    category: "string",
    purpose: "string",
    paymentId: "string",
    paidAt: "string",
    merchant: "nullableString",
    amountCents: "nonNegativeInteger",
    reimbursementCents: "nonNegativeInteger",
  },
  travelExpenseDocumentInbox: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    source: "string",
    sourceRef: "nullableString",
    documentKind: "string",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    sha256: "string",
    status: "string",
    extractedText: "nullableString",
    recognition: "nullableObject",
    matchedExpenseId: "nullableString",
    matchedPaymentId: "nullableString",
    errorCode: "nullableString",
    candidates: "array",
    attachmentId: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  invoiceDocument: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    source: "string",
    sourceRef: "nullableString",
    fileName: "string",
    mediaType: "string",
    sizeBytes: "positiveInteger",
    sha256: "string",
    extractedText: "nullableString",
    ocr: "nullableObject",
    model: "nullableObject",
    conflicts: "array",
    invoiceCode: "nullableString",
    invoiceNumber: "nullableString",
    issuedOn: "nullableString",
    sellerName: "nullableString",
    buyerName: "nullableString",
    suggestedCategory: "nullableString",
    amountExTaxCents: "nullableNumber",
    taxCents: "nullableNumber",
    totalCents: "nullableNumber",
    status: "string",
    createdBy: "string",
    updatedBy: "string",
    createdAt: "string",
    updatedAt: "string",
    contentUrl: "string",
  },
  invoiceMatch: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    invoiceId: "string",
    expenseId: "string",
    paymentId: "nullableString",
    allocatedCents: "positiveInteger",
    matchMethod: "string",
    score: "nullableNumber",
    rationale: "array",
    state: "string",
    confirmedBy: "nullableString",
    confirmedAt: "nullableString",
    revokedBy: "nullableString",
    revokedAt: "nullableString",
    createdBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseNoInvoiceConfirmation: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    expenseId: "string",
    paymentId: "nullableString",
    amountSnapshotCents: "positiveInteger",
    reason: "string",
    confirmedBy: "string",
    confirmedAt: "string",
    revokedBy: "nullableString",
    revokedAt: "nullableString",
    createdAt: "string",
    updatedAt: "string",
  },
  invoiceMatchCandidate: {
    id: "string",
    version: "positiveInteger",
    owner: "string",
    weekStart: "string",
    invoiceId: "string",
    expenseId: "string",
    paymentId: "nullableString",
    proposedCents: "positiveInteger",
    score: "positiveInteger",
    rationale: "array",
    status: "string",
    acceptedMatchId: "nullableString",
    decidedBy: "nullableString",
    decidedAt: "nullableString",
    createdBy: "string",
    createdAt: "string",
    updatedAt: "string",
  },
  travelExpenseInvoiceCoverage: {
    weekStart: "string",
    reimbursementCents: "nonNegativeInteger",
    confirmedCoverageCents: "nonNegativeInteger",
    electronicInvoiceCoverageCents: "nonNegativeInteger",
    substituteInvoiceCoverageCents: "nonNegativeInteger",
    missingInvoiceCents: "nonNegativeInteger",
    noInvoiceConfirmedCents: "nonNegativeInteger",
    unacknowledgedMissingCents: "nonNegativeInteger",
    invoiceWarehouseAvailableCents: "nonNegativeInteger",
    expenseCount: "nonNegativeInteger",
  },
  hospitalTenderNotice: {
    id: "string",
    identityKey: "string",
    sourceId: "string",
    sourceName: "string",
    city: "string",
    title: "string",
    url: "string",
    publishedAt: "string",
    noticeType: "string",
    purchaser: "string",
    projectCode: "string",
    budgetText: "string",
    deadlineText: "string",
    contentText: "string",
    hospitalNames: "array",
    sourceItemId: "string",
    contentSha256: "string",
    relevance: "string",
    matchedCustomerIds: "array",
    matchedCustomerNames: "array",
    matchReasons: "object",
    matchedNeeds: "object",
    matchScore: "nonNegativeInteger",
    revision: "positiveInteger",
    firstSeenAt: "string",
    lastSeenAt: "string",
  },
  hospitalTenderSource: {
    sourceId: "string",
    sourceName: "string",
    city: "string",
    status: "string",
    lastRunAt: "nullableString",
    lastSuccessAt: "nullableString",
    itemCount: "nonNegativeInteger",
    lastUpsertedCount: "nonNegativeInteger",
    lastRejectedCount: "nonNegativeInteger",
    lastError: "nullableString",
    updatedAt: "string",
  },
  hospitalTenderSummary: {
    totalNotices: "nonNegativeInteger",
    matchedNotices: "nonNegativeInteger",
    byNoticeType: "object",
    byRelevance: "object",
    latestRun: "nullableObject",
  },
  hospitalTenderHealth: {
    status: "string",
    sourceCount: "nonNegativeInteger",
    staleCount: "nonNegativeInteger",
    latestRun: "nullableObject",
  },
  hospitalTenderLeadConversionPreview: {
    status: "string",
    requiresHumanConfirmation: "boolean",
    notice: "object",
    customer: "object",
    conversionIdentity: "string",
    noticeSnapshotDigest: "string",
    match: "object",
    drafts: "object",
    diff: "object",
    previewDigest: "string",
  },
  hospitalTenderLeadConversionConfirmation: {
    status: "string",
    requiresHumanConfirmation: "boolean",
    replayed: "boolean",
    noticeId: "string",
    customerId: "string",
    conversionIdentity: "string",
    noticeSnapshotDigest: "string",
    previewDigest: "string",
    opportunity: "object",
    actionItem: "object",
  },
  hospitalTenderLeadConversionCancellation: {
    status: "string",
    requiresHumanConfirmation: "boolean",
    noticeId: "string",
    customerId: "string",
    conversionIdentity: "string",
    noticeSnapshotDigest: "string",
    previewDigest: "string",
  },
};

function describeValue(value) {
  if (Array.isArray(value)) return "array";
  if (value === null) return "null";
  return typeof value;
}

function isExpectedType(value, descriptor) {
  if (descriptor === "array") return Array.isArray(value);
  if (descriptor === "stringArray") return Array.isArray(value) && value.every((item) => typeof item === "string");
  if (descriptor === "object") return value !== null && typeof value === "object" && !Array.isArray(value);
  if (descriptor === "nullableObject") return value === null || (typeof value === "object" && !Array.isArray(value));
  if (descriptor === "string") return typeof value === "string";
  if (descriptor === "number") return typeof value === "number" && Number.isFinite(value);
  if (descriptor === "positiveInteger") return Number.isSafeInteger(value) && value > 0;
  if (descriptor === "nonNegativeInteger") return Number.isSafeInteger(value) && value >= 0;
  if (descriptor === "nullableString") return value === null || typeof value === "string";
  if (descriptor === "nullableNumber") return value === null || (typeof value === "number" && Number.isFinite(value));
  if (descriptor === "boolean") return typeof value === "boolean";
  throw new Error(`Unknown API contract descriptor: ${descriptor}`);
}

export function collectApiEntityErrors(entityName, value, path = entityName) {
  const schema = SALES_WORKBENCH_API_SCHEMAS[entityName];
  if (!schema) return [`${path}: unknown API contract entity "${entityName}"`];
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return [`${path}: expected object, received ${describeValue(value)}`];
  }

  const errors = [];
  for (const [field, descriptor] of Object.entries(schema)) {
    // Older cached customer projections omit additive metadata fields.
    const optional = descriptor.startsWith("optional:");
    const expectedType = optional ? descriptor.slice("optional:".length) : descriptor;
    if (optional && value[field] === undefined) continue;
    if (!(field in value)) {
      errors.push(`${path}.${field}: missing required field`);
      continue;
    }
    if (!isExpectedType(value[field], expectedType)) {
      errors.push(`${path}.${field}: expected ${expectedType}, received ${describeValue(value[field])}`);
    }
  }
  return errors;
}

export function assertApiEntity(entityName, value, path = entityName) {
  const errors = collectApiEntityErrors(entityName, value, path);
  if (errors.length > 0) {
    throw new TypeError(`Sales workbench API contract violation:\n${errors.join("\n")}`);
  }
  return value;
}

export function assertApiCollection(entityName, values, path = `${entityName}[]`) {
  if (!Array.isArray(values)) {
    throw new TypeError(`Sales workbench API contract violation:\n${path}: expected array, received ${describeValue(values)}`);
  }

  values.forEach((value, index) => assertApiEntity(entityName, value, `${path}[${index}]`));
  return values;
}
